import { Router, type IRouter } from "express";
import adminRouter from "./admin";
import usersRouter from "./users";
import companyRouter from "./company";
import facilitiesRouter from "./facilities";
import corporateRouter from "./corporate";
import regulatoryRouter from "./regulatory";
import suppliersRouter from "./suppliers";
import inspectionsRouter from "./inspections";
import inventoryRouter from "./inventory";
import batchesRouter from "./batches";
import batchImportRouter from "./batch_import";
import nonConformancesRouter from "./non_conformances";
import complaintsRouter from "./complaints";
import fieldActionsRouter from "./field_actions";
import packagingRouter from "./packaging";
import auditLogRouter from "./audit_log";
import dashboardRouter from "./dashboard";
import dashboardPrefsRouter from "./dashboard_prefs";
import licensesRouter from "./licenses";
import digestRouter from "./digest";
import notificationsRouter from "./notifications";
import capasRouter from "./capas";
import trainingRouter from "./training";
import documentsRouter from "./documents";
import documentChangeRequestsRouter from "./document_change_requests";
import supplierQualificationsRouter from "./supplierQualifications";
import lotsRouter from "./lots";
import storageRouter from "./storage";
import attachmentsRouter from "./attachments";
import labelTemplatesRouter from "./label_templates";
import recipesRouter from "./recipes";
import destructionRecordsRouter from "./destruction_records";
import regulatoryUpdatesRouter from "./regulatory_updates";
import searchRouter from "./search";
import setupStatusRouter from "./setup_status";
import helpRouter from "./help";
import metrcRouter from "./metrc";
import manifestsRouter from "./manifests";
import productSettingsRouter from "./product_settings";
import productSubtypesRouter from "./product_subtypes";
import inventoryChecksRouter from "./inventory_checks";
import managementReviewRouter from "./management_review";

const router: IRouter = Router();

router.use(usersRouter);
router.use(companyRouter);
router.use(facilitiesRouter);
router.use(corporateRouter);
router.use(regulatoryRouter);
router.use(suppliersRouter);
router.use(inspectionsRouter);
router.use(inventoryRouter);
router.use(batchesRouter);
router.use(batchImportRouter);
router.use(nonConformancesRouter);
router.use(complaintsRouter);
router.use(fieldActionsRouter);
router.use(packagingRouter);
router.use(auditLogRouter);
router.use(dashboardRouter);
router.use(dashboardPrefsRouter);
router.use(licensesRouter);
router.use(digestRouter);
router.use(notificationsRouter);
router.use(capasRouter);
router.use(trainingRouter);
router.use(documentsRouter);
router.use(documentChangeRequestsRouter);
router.use(supplierQualificationsRouter);
router.use(lotsRouter);
router.use(storageRouter);
router.use(attachmentsRouter);
router.use(labelTemplatesRouter);
router.use(recipesRouter);
router.use(destructionRecordsRouter);
router.use(regulatoryUpdatesRouter);
router.use(searchRouter);
router.use(setupStatusRouter);
router.use(helpRouter);
router.use(metrcRouter);
router.use(manifestsRouter);
router.use(productSettingsRouter);
router.use(productSubtypesRouter);
router.use(inventoryChecksRouter);
router.use(managementReviewRouter);
router.use(adminRouter);

export default router;
